//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace MGD.Umbraco.Cms.ModelsBuilder.Models
{
	/// <summary>Grouped teasers block</summary>
	[PublishedModel("groupedTeasersBlock")]
	public partial class GroupedTeasersBlock : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "groupedTeasersBlock";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GroupedTeasersBlock, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public GroupedTeasersBlock(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Background image 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("backgroundImage1")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent BackgroundImage1 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("backgroundImage1");

		///<summary>
		/// Background image 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("backgroundImage2")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent BackgroundImage2 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("backgroundImage2");

		///<summary>
		/// Background image 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("backgroundImage3")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent BackgroundImage3 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("backgroundImage3");

		///<summary>
		/// Excerpt 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("excerpt1")]
		public string Excerpt1 => this.Value<string>("excerpt1");

		///<summary>
		/// Excerpt 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("excerpt2")]
		public string Excerpt2 => this.Value<string>("excerpt2");

		///<summary>
		/// Excerpt 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("excerpt3")]
		public string Excerpt3 => this.Value<string>("excerpt3");

		///<summary>
		/// Heading 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("heading1")]
		public string Heading1 => this.Value<string>("heading1");

		///<summary>
		/// Heading 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("heading2")]
		public string Heading2 => this.Value<string>("heading2");

		///<summary>
		/// Heading 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("heading3")]
		public string Heading3 => this.Value<string>("heading3");

		///<summary>
		/// Link 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("link1")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Link1 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("link1");

		///<summary>
		/// Link 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("link2")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Link2 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("link2");

		///<summary>
		/// Link 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("link3")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Link3 => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("link3");
	}
}
