//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace MGD.Umbraco.Cms.ModelsBuilder.Models
{
	/// <summary>Resource</summary>
	[PublishedModel("resource")]
	public partial class Resource : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "resource";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Resource, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Resource(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Text (de-de)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyDeDe")]
		public global::System.Web.IHtmlString BodyDeDe => this.Value<global::System.Web.IHtmlString>("bodyDeDe");

		///<summary>
		/// Text (en-gb)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyEnGb")]
		public global::System.Web.IHtmlString BodyEnGb => this.Value<global::System.Web.IHtmlString>("bodyEnGb");

		///<summary>
		/// Text (en-us)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyEnUs")]
		public global::System.Web.IHtmlString BodyEnUs => this.Value<global::System.Web.IHtmlString>("bodyEnUs");

		///<summary>
		/// Text (es-es)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyEsEs")]
		public global::System.Web.IHtmlString BodyEsEs => this.Value<global::System.Web.IHtmlString>("bodyEsEs");

		///<summary>
		/// Text (fr-fr)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyFrFr")]
		public global::System.Web.IHtmlString BodyFrFr => this.Value<global::System.Web.IHtmlString>("bodyFrFr");

		///<summary>
		/// Text (it-it)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyItIt")]
		public global::System.Web.IHtmlString BodyItIt => this.Value<global::System.Web.IHtmlString>("bodyItIt");

		///<summary>
		/// Text (pl-pl)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodyPlPl")]
		public global::System.Web.IHtmlString BodyPlPl => this.Value<global::System.Web.IHtmlString>("bodyPlPl");

		///<summary>
		/// Text (sv-se)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("bodySvSe")]
		public global::System.Web.IHtmlString BodySvSe => this.Value<global::System.Web.IHtmlString>("bodySvSe");

		///<summary>
		/// Link to page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("link")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Link => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("link");
	}
}
