//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace MGD.Umbraco.Cms.ModelsBuilder.Models
{
	// Mixin Content Type with alias "sitemapComposition"
	/// <summary>Sitemap composition</summary>
	public partial interface ISitemapComposition : IPublishedContent
	{
		/// <summary>Hide in sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		bool SitemaHide { get; }

		/// <summary>Sitemap default change freqency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string SitemapDefaultChangeFreqency { get; }

		/// <summary>Sitemap default priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string SitemapDefaultPriority { get; }
	}

	/// <summary>Sitemap composition</summary>
	[PublishedModel("sitemapComposition")]
	public partial class SitemapComposition : PublishedContentModel, ISitemapComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "sitemapComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SitemapComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public SitemapComposition(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Hide in sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("sitemaHide")]
		public bool SitemaHide => GetSitemaHide(this);

		/// <summary>Static getter for Hide in sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static bool GetSitemaHide(ISitemapComposition that) => that.Value<bool>("sitemaHide");

		///<summary>
		/// Sitemap default change freqency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("sitemapDefaultChangeFreqency")]
		public string SitemapDefaultChangeFreqency => GetSitemapDefaultChangeFreqency(this);

		/// <summary>Static getter for Sitemap default change freqency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetSitemapDefaultChangeFreqency(ISitemapComposition that) => that.Value<string>("sitemapDefaultChangeFreqency");

		///<summary>
		/// Sitemap default priority
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("sitemapDefaultPriority")]
		public string SitemapDefaultPriority => GetSitemapDefaultPriority(this);

		/// <summary>Static getter for Sitemap default priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetSitemapDefaultPriority(ISitemapComposition that) => that.Value<string>("sitemapDefaultPriority");
	}
}
