//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace MGD.Umbraco.Cms.ModelsBuilder.Models
{
	// Mixin Content Type with alias "teaserComposition"
	/// <summary>Teaser composition</summary>
	public partial interface ITeaserComposition : IPublishedContent
	{
		/// <summary>Teaser heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		string TeaserHeading { get; }

		/// <summary>Teaser image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent TeaserImage { get; }

		/// <summary>Teaser introduction</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		global::System.Web.IHtmlString TeaserIntroduction { get; }
	}

	/// <summary>Teaser composition</summary>
	[PublishedModel("teaserComposition")]
	public partial class TeaserComposition : PublishedContentModel, ITeaserComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const string ModelTypeAlias = "teaserComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TeaserComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public TeaserComposition(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Teaser heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("teaserHeading")]
		public string TeaserHeading => GetTeaserHeading(this);

		/// <summary>Static getter for Teaser heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static string GetTeaserHeading(ITeaserComposition that) => that.Value<string>("teaserHeading");

		///<summary>
		/// Teaser image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("teaserImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TeaserImage => GetTeaserImage(this);

		/// <summary>Static getter for Teaser image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetTeaserImage(ITeaserComposition that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("teaserImage");

		///<summary>
		/// Teaser introduction
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		[ImplementPropertyType("teaserIntroduction")]
		public global::System.Web.IHtmlString TeaserIntroduction => GetTeaserIntroduction(this);

		/// <summary>Static getter for Teaser introduction</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.1")]
		public static global::System.Web.IHtmlString GetTeaserIntroduction(ITeaserComposition that) => that.Value<global::System.Web.IHtmlString>("teaserIntroduction");
	}
}
